apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: admin-service
images:
  - name: tazamaorg/admin-service
    newTag: 3.0.0
