apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: relay-service-integration-nats
images:
  - name: tazamaorg/relay-service-integration-nats
    newTag: 3.0.0
