apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: transaction-aggregation-decisioning-processor
images:
  - name: tazamaorg/tadp
    newTag: 3.0.0
