apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: typology-processor
images:
  - name: tazamaorg/typology-processor
    newTag: 3.0.0
